FROM postgres:16

RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

COPY setup-replica.sh /setup-replica.sh
RUN chmod +x /setup-replica.sh

ENTRYPOINT ["/setup-replica.sh"]
